# -*- coding: utf-8 -*-
"""Tools Manager Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vCGSncfjVnrrEATdYekmJUOrlh4KCmn-
"""

import os
import urllib.request
import json
import ssl

# 忽略 SSL 证书验证（防止下载图片报错）
ssl._create_default_https_context = ssl._create_unverified_context

# 1. 真实 AI 工具数据库 (包含官网和 Logo 链接)
# 注意：实际运行时部分 Logo 链接可能会失效，脚本会自动处理
tools_db = [
    # --- 国产热门 ---
    {
        "id": "cn-001", "name": "DeepSeek", "category": "text",
        "desc": "深度求索开发的国产开源大模型，推理能力惊人。",
        "url": "https://www.deepseek.com/",
        "logo_url": "https://pbs.twimg.com/profile_images/1780076211750699008/7o_eQeg2_400x400.jpg",
        "tags": ["国产之光", "开源", "免费"]
    },
    {
        "id": "cn-002", "name": "Kimi智能助手", "category": "text",
        "desc": "月之暗面科技推出的超长文本处理 AI，支持 20 万字上下文。",
        "url": "https://kimi.moonshot.cn/",
        "logo_url": "https://img.qcog.cn/submission/2024/23018285/c10e147f8774e12e75344386926943c7.png",
        "tags": ["长文本", "文件分析", "免费"]
    },
    {
        "id": "cn-003", "name": "豆包", "category": "text",
        "desc": "字节跳动出品的 AI 对话助手，语音交互体验极佳。",
        "url": "https://www.doubao.com/",
        "logo_url": "https://lf-flow-web-cdn.doubao.com/obj/flow-web-cdn/doubao/web/logo-icon.png",
        "tags": ["字节跳动", "语音", "免费"]
    },
    {
        "id": "cn-004", "name": "通义千问", "category": "text",
        "desc": "阿里巴巴研发的超大规模语言模型，全能型助手。",
        "url": "https://tongyi.aliyun.com/",
        "logo_url": "https://img.alicdn.com/imgextra/i4/O1CN016y5q5H1uH7H8u5H5H_!!6000000006013-2-tps-200-200.png",
        "tags": ["阿里", "全能", "免费"]
    },
    {
        "id": "cn-005", "name": "即梦AI", "category": "image",
        "desc": "字节跳动推出的 AI 绘画与视频生成工具，效果惊艳。",
        "url": "https://jimeng.jianying.com/",
        "logo_url": "https://p3-pc-sign.douyinpic.com/tos-cn-i-0813c001/oAABqC6A9AAg9AAg9AAg9AAg9.png?x-expires=1740000000&x-signature=image_logo",
        "tags": ["绘画", "视频", "字节"]
    },
    {
        "id": "cn-006", "name": "秘塔AI搜索", "category": "search",
        "desc": "没有广告的 AI 搜索引擎，精准检索并生成摘要。",
        "url": "https://metaso.cn/",
        "logo_url": "https://metaso.cn/favicon.ico",
        "tags": ["搜索", "无广告", "学术"]
    },

    # --- 国际顶流 ---
    {
        "id": "us-001", "name": "ChatGPT", "category": "text",
        "desc": "OpenAI 开启 AI 时代的里程碑产品，GPT-4o 极其强大。",
        "url": "https://chat.openai.com/",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/1024px-ChatGPT_logo.svg.png",
        "tags": ["OpenAI", "最强", "付费/免费"]
    },
    {
        "id": "us-002", "name": "Midjourney", "category": "image",
        "desc": "目前公认生成质量最高的 AI 绘画工具，艺术感极强。",
        "url": "https://www.midjourney.com/",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/e/ed/Midjourney_Emblem.png",
        "tags": ["绘画", "艺术", "付费"]
    },
    {
        "id": "us-003", "name": "Claude 3", "category": "text",
        "desc": "Anthropic 出品，逻辑推理与代码能力超越 GPT-4 的强力模型。",
        "url": "https://claude.ai/",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Claude_AI_logo.png/600px-Claude_AI_logo.png",
        "tags": ["逻辑强", "拟人化", "免费"]
    },
    {
        "id": "us-004", "name": "Sora", "category": "video",
        "desc": "OpenAI 发布的文生视频模型，虽然未公测但已震撼世界。",
        "url": "https://openai.com/sora",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/OpenAI_Logo.svg/1024px-OpenAI_Logo.svg.png",
        "tags": ["视频", "未发布", "OpenAI"]
    },
    {
        "id": "us-005", "name": "Suno", "category": "audio",
        "desc": "文字一键生成 3 分钟广播级歌曲，音乐界的 ChatGPT。",
        "url": "https://suno.com/",
        "logo_url": "https://yt3.googleusercontent.com/Vi9O6rI6CqA8YgV4y1y4y1y4=s900-c-k-c0x00ffffff-no-rj",
        "tags": ["音乐", "创作", "热门"]
    },
    {
        "id": "us-006", "name": "Stable Diffusion", "category": "image",
        "desc": "开源 AI 绘画的基石，支持本地部署，可控性最高。",
        "url": "https://stability.ai/",
        "logo_url": "https://stability.ai/images/stability-ai-logo.png",
        "tags": ["开源", "本地", "绘画"]
    },
     {
        "id": "dev-001", "name": "GitHub Copilot", "category": "code",
        "desc": "AI 编程助手，直接在编辑器中自动补全代码。",
        "url": "https://github.com/features/copilot",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/GitHub_mark_wrapper.svg/512px-GitHub_mark_wrapper.svg.png",
        "tags": ["编程", "微软", "付费"]
    },
    {
        "id": "dev-002", "name": "Trae", "category": "code",
        "desc": "字节跳动推出的自适应 AI IDE，你的智能编程搭档。",
        "url": "https://www.trae.ai/",
        "logo_url": "https://lf-flow-web-cdn.doubao.com/obj/flow-web-cdn/doubao/web/logo-icon.png", # 暂用豆包logo替代
        "tags": ["编程", "IDE", "免费"]
    }
]

# 2. 配置路径
ASSETS_DIR = "assets/logos"
JS_FILE_PATH = "js/tools_data.js"

def setup_directories():
    if not os.path.exists(ASSETS_DIR):
        os.makedirs(ASSETS_DIR)
        print(f"✅ 创建目录: {ASSETS_DIR}")

    js_dir = os.path.dirname(JS_FILE_PATH)
    if not os.path.exists(js_dir):
        os.makedirs(js_dir)
        print(f"✅ 创建目录: {js_dir}")

def download_logo(url, name):
    # 清理文件名
    safe_name = "".join([c for c in name if c.isalnum() or c in ('-','_')]).lower()
    file_path = f"{ASSETS_DIR}/{safe_name}.png"

    # 如果文件已存在，跳过
    if os.path.exists(file_path):
        return file_path

    try:
        # 伪装 User-Agent 防止被拦截
        req = urllib.request.Request(
            url,
            data=None,
            headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
        )
        with urllib.request.urlopen(req, timeout=10) as response, open(file_path, 'wb') as out_file:
            out_file.write(response.read())
        print(f"📥 下载成功: {name}")
        return file_path
    except Exception as e:
        print(f"⚠️ 下载失败 [{name}]: {e}")
        return None

def main():
    setup_directories()

    final_data = []

    print("🚀 开始更新 AI 工具库...")

    for tool in tools_db:
        # 下载图片
        local_path = download_logo(tool["logo_url"], tool["name"])

        # 更新工具数据中的 image 字段
        tool_entry = tool.copy()
        if local_path:
            tool_entry["logo"] = local_path
        else:
            tool_entry["logo"] = "assets/logos/default.png" # 需准备一个默认图

        # 移除远程 url 字段，只保留本地 path (或者两个都留)
        del tool_entry["logo_url"]

        final_data.append(tool_entry)

    # 生成 JS 文件
    js_content = f"// Auto-generated by tools_manager.py\nconst aiToolsData = {json.dumps(final_data, indent=4, ensure_ascii=False)};"

    with open(JS_FILE_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"\n✨ 完成! 数据已写入 {JS_FILE_PATH}")
    print(f"📊 共收录 {len(final_data)} 个工具")

if __name__ == "__main__":
    main()